services:
  api:
    container_name: alertcity-api
    image: alertcity-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - JWT_SECRET=${JWT_SECRET}
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - COMPANY_NAME=${COMPANY_NAME}
      - CAPTCHA_SECRET_KEY=${CAPTCHA_SECRET_KEY}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    networks:
      - dts

networks:
  dts:
    external: true